# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7d92c6f8-53b4-4559-889e-b336e5326f57";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7630-8603";
      fsType = "vfat";
    };

  fileSystems."/mnt" =
    { device = "/dev/disk/by-uuid/c1740498-2f0b-4cfa-bcea-4abda2ac9002";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/633fe3c8-15f7-4892-b27d-d069b5e34355"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
